export const songList = [
  {
    id: "1",
    title: "Ain't no Sunshine",
    artist: "Bill Withers",
    doc: "aint_no_sunshine",
  },
  { id: "2", title: "Ain't nobody", artist: "Shaka Khan", doc: "aint_nobody" },
  { id: "3", title: "All of me", artist: "John Legend", doc: "all_of_me" },
  { id: "4", title: "Als ze er niet is", artist: "de Dijk", doc: "als_ze_er" },
  { id: "5", title: "", artist: "", doc: "" },
  { id: "6", title: "", artist: "", doc: "" },
  { id: "7", title: "", artist: "", doc: "" },
  { id: "8", title: "", artist: "", doc: "" },
  { id: "9", title: "", artist: "", doc: "" },
  { id: "10", title: "", artist: "", doc: "" },
  { id: "11", title: "", artist: "", doc: "" },
  { id: "12", title: "", artist: "", doc: "" },
  { id: "13", title: "", artist: "", doc: "" },
  { id: "14", title: "", artist: "", doc: "" },
  { id: "15", title: "", artist: "", doc: "" },
  { id: "16", title: "", artist: "", doc: "" },
  { id: "17", title: "", artist: "", doc: "" },
];
