export const songList = [
  {
    id: "1",
    title: "Ain't no Sunshine",
    artist: "Bill Withers",
    doc: "aint_no_sunshine",
  },
  { id: "2", title: "Ain't nobody", artist: "Shaka Khan", doc: "aint_nobody" },
  { id: "3", title: "All of me", artist: "John Legend", doc: "all_of_me" },
  { id: "4", title: "Als ze er niet is", artist: "de Dijk", doc: "als_ze_er" },
  { id: "5", title: "Anders Anders", artist: "Herman van Veen", doc: "anders" },
  {
    id: "6",
    title: "Een Beetje Verliefd",
    artist: "Andre Hazes",
    doc: "beetje_verliefd",
  },
  { id: "7", title: "Blauwe Dag", artist: "Suzan & Freek", doc: "blauwe_dag" },
  {
    id: "8",
    title: "The Book Of Love",
    artist: "Peter Gabriel",
    doc: "book_of_love",
  },
  { id: "9", title: "the Cup Song", artist: "Anna Kendrick", doc: "cup_song" },
  {
    id: "10",
    title: "Dates in Pickup Trucks",
    artist: "Kassi Ashton",
    doc: "dates_in_pickup",
  },
  {
    id: "11",
    title: "Don't Know Why",
    artist: "Norah Jones",
    doc: "dont_know_why",
  },
  { id: "12", title: "Dreams", artist: "Fleetwood Mac", doc: "dreams" },
  { id: "13", title: "Flowers", artist: "Miley Cyrus", doc: "flowers" },
  {
    id: "14",
    title: "Can't help Falling in Love",
    artist: "Elvis Presley",
    doc: "cant_help",
  },
  { id: "15", title: "", artist: "", doc: "" },
  { id: "16", title: "", artist: "", doc: "" },
  { id: "17", title: "", artist: "", doc: "" },
];
